[package]
name = "shulkerbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.197", features = ["derive"], optional = true }
zip = "0.6.6"
